### ISSUE TITLE
 phantomjs exit with code 100, open url fail (stream "error")

### ISSUE THREAD

**Issue by wanglong167** [node-modules/webcamera#6]
return s.emit('error', err);的时候报错

WebCameraOpenURLError: phantomjs exit with code 100, open url fail
    at ChildProcess.<anonymous> (E:\workRoot\www_node\webcamera\lib\web_camera.js:166:19)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

 是不是和你的列队有关系？

**Comment by wanglong167** [comment]
camera.shotStream('asdfjhasjhkdfjhjhzxcvxxx.com',fun(){})
